// crtm-bundle builds portable tool bundles and optional Go embed declarations.
package main

import (
	"context"
	"flag"
	"fmt"
	"go/format"
	"go/token"
	"os"
	"os/signal"
	"path/filepath"
	"sort"
	"strings"

	crtm "github.com/chainreactors/crtm/pkg"
)

func main() {
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt)
	defer stop()
	if err := run(ctx, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(ctx context.Context, args []string) error {
	flags := flag.NewFlagSet("crtm-bundle", flag.ContinueOnError)
	config := flags.String("config", "bundle.yaml", "bundle selection")
	targetName := flags.String("target", crtm.CurrentTarget().String(), "target GOOS/GOARCH")
	output := flags.String("output", "bundle", "output directory (Go package directory with -package)")
	packageName := flags.String("package", "", "generate EmbeddedBundle() in this Go package")
	tag := flags.String("tag", "arsenal_embed", "build tag for generated Go file")
	metadataOnly := flags.Bool("metadata-only", false, "generate tool metadata without downloading binaries (requires -package)")
	if err := flags.Parse(args); err != nil {
		return err
	}
	if flags.NArg() != 0 {
		return fmt.Errorf("unexpected arguments: %v", flags.Args())
	}
	if *packageName != "" && (!token.IsIdentifier(*packageName) || !token.IsIdentifier(*tag)) {
		return fmt.Errorf("invalid package or build tag")
	}
	if *metadataOnly && *packageName == "" {
		return fmt.Errorf("-metadata-only requires -package")
	}
	goos, goarch, ok := strings.Cut(*targetName, "/")
	if !ok {
		return fmt.Errorf("target must be GOOS/GOARCH")
	}
	target := crtm.Target{GOOS: goos, GOARCH: goarch}
	spec, err := crtm.LoadBundleSpec(*config)
	if err != nil {
		return err
	}
	if *metadataOnly {
		return writeSpec(*output, *packageName, spec)
	}
	assets := *output
	if *packageName != "" {
		assets = filepath.Join(*output, "assets", goos+"_"+goarch)
	}
	dir, err := crtm.BuildBundle(ctx, spec, target, assets)
	if err != nil {
		return err
	}
	if *packageName != "" {
		if err := writeSpec(*output, *packageName, spec); err != nil {
			return err
		}
		if err := writeEmbed(*output, dir, *packageName, *tag, target); err != nil {
			return err
		}
	}
	fmt.Println(dir)
	return nil
}

func writeSpec(output, packageName string, spec crtm.BundleSpec) error {
	var source strings.Builder
	fmt.Fprintf(&source, "// Code generated by crtm-bundle; DO NOT EDIT.\n\npackage %s\n\nimport (\ncrtm %q\n", packageName, "github.com/chainreactors/crtm/pkg")
	if len(spec.CustomTools) > 0 {
		fmt.Fprintf(&source, "%q\n", "github.com/chainreactors/crtm/pkg/registry")
	}
	fmt.Fprintf(&source, ")\n\nvar ToolSpec = crtm.BundleSpec{\nID: %q,\nTools: ", spec.ID)
	writeSelection(&source, spec.Tools)
	if len(spec.Platforms) > 0 {
		source.WriteString("Platforms: map[string]crtm.ToolSelection{\n")
		platforms := make([]string, 0, len(spec.Platforms))
		for platform := range spec.Platforms {
			platforms = append(platforms, platform)
		}
		sort.Strings(platforms)
		for _, platform := range platforms {
			fmt.Fprintf(&source, "%q: ", platform)
			writeSelection(&source, spec.Platforms[platform])
		}
		source.WriteString("},\n")
	}
	if len(spec.CustomTools) > 0 {
		fmt.Fprintf(&source, "CustomTools: %#v,\n", spec.CustomTools)
	}
	source.WriteString("}\n")
	return writeGo(output, "bundle_spec_generated.go", []byte(source.String()))
}

func writeSelection(source *strings.Builder, tools crtm.ToolSelection) {
	source.WriteString("map[string]string{\n")
	names := make([]string, 0, len(tools))
	for name := range tools {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		fmt.Fprintf(source, "%q: %q,\n", name, tools[name])
	}
	source.WriteString("},\n")
}

func writeEmbed(output, dir, packageName, tag string, target crtm.Target) error {
	rel, err := filepath.Rel(output, dir)
	if err != nil {
		return err
	}
	path := filepath.ToSlash(rel)
	source := fmt.Sprintf(`// Code generated by crtm-bundle; DO NOT EDIT.
//go:build %s && %s && %s

package %s

import (
	"embed"
	"io/fs"

	crtm "github.com/chainreactors/crtm/pkg"
)

//go:embed %s
var bundleFiles embed.FS

func EmbeddedBundle() (*crtm.Bundle, error) {
	files, err := fs.Sub(bundleFiles, %q)
	if err != nil { return nil, err }
	return crtm.OpenBundle(files)
}
`, tag, target.GOOS, target.GOARCH, packageName, path, path)
	return writeGo(output, "bundle_generated_"+target.GOOS+"_"+target.GOARCH+".go", []byte(source))
}

func writeGo(output, name string, source []byte) error {
	body, err := format.Source(source)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(output, 0755); err != nil {
		return err
	}
	f, err := os.CreateTemp(output, ".bundle-go-*")
	if err != nil {
		return err
	}
	defer os.Remove(f.Name())
	defer f.Close()
	if _, err := f.Write(body); err != nil {
		return err
	}
	if err := f.Close(); err != nil {
		return err
	}
	return os.Rename(f.Name(), filepath.Join(output, name))
}
