name: 🎉 Release Binary

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: "Check out code"
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      
      - name: "Set up Go"
        uses: actions/setup-go@v4
        with: 
          go-version: 1.20.x
          check-latest: true
          cache: true
      
      - name: "Create release on GitHub"
        uses: goreleaser/goreleaser-action@v4
        with: 
          args: "release"
          version: latest
          workdir: .
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
